name: Build and Test

on:
  push:
    branches: [ master, pipelines ]
  pull_request:
    branches: [ master, pipelines ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://nuget.pkg.github.com/SeanoNET/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Generate package
      run: dotnet pack --no-build -c Release -o .
    - name: Push package to registry
      run: dotnet nuget push S3ZipSharp.*.nupkg